<script>
    import { onMount } from 'svelte';

    // Global configurations
    let apiBase = $state("https://jumbotron.lynn89sudo.hackclub.app");
    let masterKey = $state("");

    onMount(() => {
        masterKey = localStorage.getItem("dev_master_key") || "";
    });

    function saveKey(val) {
        masterKey = val;
        localStorage.setItem("dev_master_key", val);
    }

    // Single reactive object for all terminal console views
    let UI = $state({
        resGetData: "",
        resAcceptedEmails: "",
        resAddEmail: "",
        resRemoveEmail: "",
        resMutate: "",
        resMasterOverride: "",
        resForceCache: "",
        resGenBackup: "",
        resCreateSession: ""
    });

    // Helper mapping function to update the single state object reference safely
    function setTerminalOutput(endpoint, textValue) {
        let key = "";
        if (endpoint === '/data') key = "resGetData";
        if (endpoint === '/acceptedEmails') key = "resAcceptedEmails";
        if (endpoint === '/addEmail') key = "resAddEmail";
        if (endpoint === '/removeEmail') key = "resRemoveEmail";
        if (endpoint === '/mutate') key = "resMutate";
        if (endpoint === '/createSession') key = "resCreateSession";
        if (endpoint === '/masterOverride') key = "resMasterOverride";
        if (endpoint === '/forceCache') key = "resForceCache";
        if (endpoint === '/genBackup') key = "resGenBackup";

        if (key) {
            // Overwriting the absolute object root reference forces Svelte 5 to update the DOM
            UI = { ...UI, [key]: textValue };
        }
    }

    // Input parameters mapping variables
    let getDataParam = $state({ eventName: "NYC" });
    let getEmailsParam = $state({ cityName: "NYC" });
    let addEmailParam = $state({ cityName: "NYC", emailAddress: "" });
    let removeEmailParam = $state({ cityName: "NYC", emailAddress: "" });
    let mutateParam = $state({ cityName: "NYC", data: '{"status": "active"}' });
    let overrideParam = $state({ eventsNew: '[]', sessionsNew: '[]' });
    let sessionParam = $state({ code: "", cityName: "NYC" });

    // Streamlined Fetch Logic Wrapper
    async function runRequest(endpoint, method, payload = null, queryParams = null) {
        setTerminalOutput(endpoint, "⏳ Sending Request...");
        try {
            let url = `${apiBase}${endpoint}`;
            if (queryParams) {
                const searchParams = new URLSearchParams();
                Object.entries(queryParams).forEach(([k, v]) => {
                    if (v !== undefined && v !== null) searchParams.append(k, v);
                });
                url += `?${searchParams.toString()}`;
            }

            const options = {
                method: method,
                headers: { 
                    "Content-Type": "application/json",
                    "Accept": "application/json"
                }
            };

            if (payload && (method === 'POST' || method === 'PUT')) {
                options.body = JSON.stringify(payload);
            }

            const res = await fetch(url, options);
            const text = await res.text();
            
            try {
                const jsonParsed = JSON.parse(text);
                setTerminalOutput(endpoint, `[Status ${res.status}] \n${JSON.stringify(jsonParsed, null, 2)}`);
            } catch {
                setTerminalOutput(endpoint, `[Status ${res.status} Non-JSON Response] \n${text}`);
            }
        } catch (err) {
            setTerminalOutput(endpoint, `🚨 Network Error: ${err.message}`);
        }
    }
</script>

<main>
    <h1>Jumbotron API Sandbox Tool</h1>
    <p>Disclosure: this entire page is generated by Artificial Intelligence; exceptions to this are styles.css</p>
    
    <!-- Global Controls Box -->
    <div class="box global-box">
        <h3>🔑 Global Configuration Credentials</h3>
        <label>
            Backend Base API URL:
            <input type="text" bind:value={apiBase} placeholder="https://..." />
        </label>
        <label>
            Master Authentication Key (`authKey` / `masterKey`):
            <input type="password" value={masterKey} oninput={(e) => saveKey(e.target.value)} placeholder="Enter your secret master key" />
        </label>
    </div>

    <div class="grid">
        <!-- GET /data -->
        <div class="box">
            <h4>🟢 GET `/data`</h4>
            <p class="desc">Fetch liveshare public state configurations</p>
            <label>Event Name: <input type="text" bind:value={getDataParam.eventName} /></label>
            <button onclick={() => runRequest('/data', 'GET', null, { eventName: getDataParam.eventName })}>Run Request</button>
            <pre>{UI.resGetData}</pre>
        </div>

        <!-- GET /acceptedEmails -->
        <div class="box">
            <h4>🟢 GET `/acceptedEmails`</h4>
            <p class="desc">View all allowed event operators</p>
            <label>City Name: <input type="text" bind:value={getEmailsParam.cityName} /></label>
            <button onclick={() => runRequest('/acceptedEmails', 'GET', null, { authKey: masterKey, cityName: getEmailsParam.cityName })}>Run Request</button>
            <pre>{UI.resAcceptedEmails}</pre>
        </div>

        <!-- POST /addEmail -->
        <div class="box">
            <h4>🔵 POST `/addEmail`</h4>
            <p class="desc">Whitelist an organizer email profile</p>
            <label>City Name: <input type="text" bind:value={addEmailParam.cityName} /></label>
            <label>Email Address: <input type="email" bind:value={addEmailParam.emailAddress} placeholder="name@domain.com" /></label>
            <button onclick={() => runRequest('/addEmail', 'POST', { authKey: masterKey, cityName: addEmailParam.cityName, emailAddress: addEmailParam.emailAddress })}>Run Request</button>
            <pre>{UI.resAddEmail}</pre>
        </div>

        <!-- POST /removeEmail -->
        <div class="box">
            <h4>🔵 POST `/removeEmail`</h4>
            <p class="desc">De-authorize an organizer email profile</p>
            <label>City Name: <input type="text" bind:value={removeEmailParam.cityName} /></label>
            <label>Email Address: <input type="email" bind:value={removeEmailParam.emailAddress} /></label>
            <button onclick={() => runRequest('/removeEmail', 'POST', { authKey: masterKey, cityName: removeEmailParam.cityName, emailAddress: removeEmailParam.emailAddress })}>Run Request</button>
            <pre>{UI.resRemoveEmail}</pre>
        </div>

        <!-- POST /mutate -->
        <div class="box">
            <h4>🔵 POST `/mutate` (As Master)</h4>
            <p class="desc">Directly rewrite liveshare data contents</p>
            <label>City Name: <input type="text" bind:value={mutateParam.cityName} /></label>
            <label>Data (JSON String Payload): <textarea bind:value={mutateParam.data}></textarea></label>
            <button onclick={() => {
                try {
                    const parsed = JSON.parse(mutateParam.data);
                    runRequest('/mutate', 'POST', { auth: masterKey, cityName: mutateParam.cityName, data: parsed });
                } catch(e) {
                    setTerminalOutput('/mutate', "Malformed JSON payload string structural syntax error.");
                }
            }}>Run Request</button>
            <pre>{UI.resMutate}</pre>
        </div>

        <!-- POST /createSession -->
        <div class="box">
            <h4>🔵 POST `/createSession`</h4>
            <p class="desc">Submit incoming browser OAuth parameters code</p>
            <label>City Name: <input type="text" bind:value={sessionParam.cityName} /></label>
            <label>OAuth Auth Code: <input type="text" bind:value={sessionParam.code} placeholder="Code parameter from URL string" /></label>
            <button onclick={() => runRequest('/createSession', 'POST', { code: sessionParam.code, cityName: sessionParam.cityName })}>Run Request</button>
            <pre>{UI.resCreateSession}</pre>
        </div>

        <!-- POST /masterOverride -->
        <div class="box">
            <h4>🚨 POST `/masterOverride`</h4>
            <p class="desc">Force wholesale internal memory database replacements</p>
            <label>Events Array JSON: <textarea bind:value={overrideParam.eventsNew}></textarea></label>
            <label>Sessions Array JSON: <textarea bind:value={overrideParam.sessionsNew}></textarea></label>
            <button onclick={() => {
                try {
                    runRequest('/masterOverride', 'POST', {
                        authKey: masterKey,
                        eventsNew: JSON.parse(overrideParam.eventsNew),
                        sessionsNew: JSON.parse(overrideParam.sessionsNew)
                    });
                } catch(e) { setTerminalOutput('/masterOverride', "Parsing fields object formatting compilation failure."); }
            }}>Run Request</button>
            <pre>{UI.resMasterOverride}</pre>
        </div>

        <!-- Administrative Actions -->
        <div class="box admin-actions">
            <h4>⚙️ System Core Utilities</h4>
            <p class="desc">System actions utilizing master privileges</p>
            
            <div class="action-row">
                <button onclick={() => runRequest('/forceCache', 'POST', { authKey: masterKey })}>Run `/forceCache`</button>
                <pre>{UI.resForceCache}</pre>
            </div>
            
            <div class="action-row">
                <button onclick={() => runRequest('/genBackup', 'POST', { authKey: masterKey })}>Run `/genBackup` (Slack)</button>
                <pre>{UI.resGenBackup}</pre>
            </div>
        </div>
    </div>
</main>

<style>
    :global(body) {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        background-color: #f4f6f8;
        color: #333;
        margin: 0;
        padding: 20px;
    }
    main {
        max-width: 1200px;
        margin: 0 auto;
    }
    h1 { color: #1e293b; margin-bottom: 24px; text-align: center;}
    h3, h4 { margin: 0 0 8px 0; color: #1e293b; }
    p.desc { margin: 0 0 16px 0; font-size: 0.85rem; color: #64748b; font-style: italic; }
    
    .box {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        padding: 20px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        display: flex;
        flex-direction: column;
    }
    .global-box {
        background: #f8fafc;
        border: 2px solid #cbd5e1;
        margin-bottom: 24px;
    }
    
    .grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(550px, 1fr));
        gap: 20px;
    }
    
    label {
        display: flex;
        flex-direction: column;
        gap: 4px;
        font-size: 0.85rem;
        font-weight: 600;
        color: #475569;
        margin-bottom: 12px;
    }
    
    input, textarea {
        padding: 8px 12px;
        border: 1px solid #cbd5e1;
        border-radius: 6px;
        font-family: inherit;
        font-size: 0.9rem;
    }
    textarea { height: 60px; resize: vertical; font-family: monospace; }
    input:focus, textarea:focus { outline: 2px solid #3b82f6; }
    
    button {
        background-color: #2563eb;
        color: white;
        border: none;
        padding: 10px;
        border-radius: 6px;
        font-weight: 600;
        cursor: pointer;
        transition: background 0.2s;
    }
    button:hover { background-color: #1d4ed8; }
    
    pre {
        background: #0f172a;
        color: #38bdf8;
        padding: 12px;
        border-radius: 6px;
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
        font-size: 0.8rem;
        overflow-x: auto;
        white-space: pre-wrap;
        word-break: break-all;
        margin-top: 12px;
        max-height: 200px;
        overflow-y: auto;
    }
    
    .admin-actions .action-row {
        border-bottom: 1px solid #f1f5f9;
        padding-bottom: 12px;
        margin-bottom: 12px;
    }
    .admin-actions .action-row:last-child { border: none; margin: 0; padding: 0; }
</style>